version: 2
jobs:
    install:
        docker:
            - image: circleci/node:8.10.0
        steps:
            - checkout
            - restore_cache:
                  key: dependency-cache-{{ checksum "package-lock.json" }}
            - run:
                  name: Install project dependencies
                  command: yarn install
            - save_cache:
                  key: dependency-cache-{{ checksum "package-lock.json" }}
                  paths:
                      - node_modules
    test:
        docker:
            - image: circleci/node:8.10.0
        steps:
            - checkout
            - run: yarn test
workflows:
    version: 2
    install_and_test:
        jobs:
            - install
            - test:
                  requires:
                      - install
